/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combat.management;

import java.awt.GridBagConstraints;
import static java.awt.GridBagConstraints.FIRST_LINE_START;
import java.awt.GridBagLayout;

/**
 *
 * @author Ahmed
 */
public class Dashboard extends javax.swing.JPanel {
    private LeftMainNavigation leftMainNavigation;
    //private LeftMainNavigation leftMainNavigation2;
    private Users users;
    final static boolean shouldFill = true;
    final static boolean shouldWeightX = true;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();

        this.setLayout(new GridBagLayout());
       
        GridBagConstraints c = new GridBagConstraints();
        
        if (shouldFill) {
            c.fill = GridBagConstraints.HORIZONTAL;
        }
        
        leftMainNavigation = new LeftMainNavigation();
        if (shouldWeightX) {
            c.weightx = 0.2;
	}
	c.fill = GridBagConstraints.HORIZONTAL;
	c.gridx = 0;
	c.gridy = 0;
        //c.anchor = FIRST_LINE_START;
	this.add(leftMainNavigation, c);

        users = new Users();
	c.fill = GridBagConstraints.HORIZONTAL;
	c.weightx = 0.8;
	c.gridx = 1;
	c.gridy = 0;
        //c.anchor = FIRST_LINE_START;
	this.add(users, c);
        
//        this.add(leftMainNavigation);
//        this.add(leftMainNavigation2);
        
        this.setVisible(true);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(900, 900));
        setPreferredSize(new java.awt.Dimension(900, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
