/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combat.management;

import combat.management.Config.CombatConfig;
import combat.management.Models.Student;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ahmed
 */
public class UserPanel extends javax.swing.JPanel/* implements MouseListener*/ {
    private String[] randomFileJPGs = { "karartekid.jpg", "lee1.jpg", "lee2.jpg", "lee3.jpg" };
    private Student _s;
    /**
     * Creates new form UserPanel
     */
    public UserPanel(Student s) {
        initComponents();
                
        _s = s;
        
        Name.setText(GetStudentName());
        //setBorder(new LineBorder(Color.GREEN, 1));
        
        String userImageDirectory = CombatConfig.UserImagesDirectory();
        
        System.out.println(userImageDirectory);
        
        int random = (int)(Math.random() * 50);
        int limit = 4;
        
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(userImageDirectory + randomFileJPGs[random % limit]));

            Image dimg = img.getScaledInstance(Picture.getPreferredSize().width, Picture.getPreferredSize().height, Image.SCALE_SMOOTH);
            
            this.Picture.setIcon(new ImageIcon(dimg));
            
            this.Picture.setHorizontalAlignment(JLabel.CENTER);
        }
        catch (Exception e) {
        }
    }
    
    public String GetStudentName() {
        return _s.Firstname + " " + _s.Lastname;
    }
    
    public Student getStudent() {
        return _s;
    }
    
//    public void mouseClicked(MouseEvent e) {
////        grid.setVisible(false);
////        userPagePanel.setVisible(true);
//    }
//   
//    public void mousePressed(MouseEvent e) {
//        
//    }
//
//    public void mouseReleased(MouseEvent e) {
//        
//    }
//
//    public void mouseEntered(MouseEvent e) {
//        
//    }
//
//    public void mouseExited(MouseEvent e) {
//        
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Picture = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setMaximumSize(new java.awt.Dimension(130, 170));
        setMinimumSize(new java.awt.Dimension(100, 150));
        setPreferredSize(new java.awt.Dimension(110, 160));
        setVerifyInputWhenFocusTarget(false);

        Picture.setMaximumSize(new java.awt.Dimension(1100, 1400));
        Picture.setPreferredSize(new java.awt.Dimension(110, 140));

        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Picture;
    // End of variables declaration//GEN-END:variables
}